alter table IMPORTDATA_IMPORT_LOG add constraint FK_IMPORTDATA_IMPORT_LOG_FILE_NAME foreign key (FILE_NAME_ID) references SYS_FILE(ID);
create index IDX_IMPORTDATA_IMPORT_LOG_FILE_NAME on IMPORTDATA_IMPORT_LOG (FILE_NAME_ID);
