alter table IMPORTDATA_IMPORT_FILE add constraint FK_IMPORTDATA_IMPORT_FILE_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_IMPORTDATA_IMPORT_FILE_FILE on IMPORTDATA_IMPORT_FILE (FILE_ID);
