-- begin IMPORTDATA_IMPORT_LOG
alter table IMPORTDATA_IMPORT_LOG add constraint FK_IMPORTDATA_IMPORT_LOG_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table IMPORTDATA_IMPORT_LOG add constraint FK_IMPORTDATA_IMPORT_LOG_IMPORT_SCENARIO foreign key (IMPORT_SCENARIO_ID) references IMPORTDATA_IMPORT_SCENARIO(ID)^
create index IDX_IMPORTDATA_IMPORT_LOG_IMPORT_SCENARIO on IMPORTDATA_IMPORT_LOG (IMPORT_SCENARIO_ID)^
create index IDX_IMPORTDATA_IMPORT_LOG_FILE on IMPORTDATA_IMPORT_LOG (FILE_ID)^
-- end IMPORTDATA_IMPORT_LOG
-- begin IMPORTDATA_IMPORT_SCENARIO
alter table IMPORTDATA_IMPORT_SCENARIO add constraint FK_IMPORTDATA_IMPORT_SCENARIO_TEMPLATE foreign key (TEMPLATE_ID) references SYS_FILE(ID)^
create index IDX_IMPORTDATA_IMPORT_SCENARIO_TEMPLATE on IMPORTDATA_IMPORT_SCENARIO (TEMPLATE_ID)^
-- end IMPORTDATA_IMPORT_SCENARIO
-- begin IMPORTDATA_IMPORT_LOG_RECORD
alter table IMPORTDATA_IMPORT_LOG_RECORD add constraint FK_IMPORTDATA_IMPORT_LOG_RECORD_IMPORT_LOG foreign key (IMPORT_LOG_ID) references IMPORTDATA_IMPORT_LOG(ID)^
create index IDX_IMPORTDATA_IMPORT_LOG_RECORD_IMPORT_LOG on IMPORTDATA_IMPORT_LOG_RECORD (IMPORT_LOG_ID)^
-- end IMPORTDATA_IMPORT_LOG_RECORD
